server:
  port: 8761                    # 指定该Eureka实例的端口
eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  server:
      #开启自我保护模式
      enable-self-preservation: false
      #清理无效节点,默认60*1000毫秒,即60秒
      eviction-interval-timer-in-ms: 5000

# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756