spring:
  application:
    name: gateway-service
  datasource:
      druid:
        url: jdbc:mysql://47.75.85.48:3306/spring-cloud-test?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: MyNewPass4!

server:
  port: 8768
eureka:
  instance:
      hostname: 111.231.189.44
      appname: gateway
      instance-id: http://111.231.189.44:${server.port}
      prefer-ip-address: true
      ip-address: 111.231.189.44
  client:
    serviceUrl:
      defaultZone: http://111.231.189.44:8761/eureka
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true
zuul:
  prefix: /api # 设置一个公共的前缀
#  ignored-services: '*' #此配置表名忽略所有默认路由，都由配置文件决定
  host:
      connect-timeout-millis: 20000
      socket-timeout-millis: 20000
  routes:
    order-service:
      path: /order/**
      serviceId: order-service
    commodity-service:
      path: /commodity/**
      serviceId: commodity-service
    account-service:
      path: /account/**
      serviceId: account-service
    payment-service:
      path: /payment/**
      serviceId: payment-service
    coupon-service:
      path: /coupon/**
      serviceId: coupon-service