server:
  port: 8765
# druid
spring:
  application:
    name: payment-service
  datasource:
    druid:
      url: jdbc:mysql://111.231.189.44:3306/spring-cloud-paycenter?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: mark2019
  aop:
    auto: true
  freemarker:
    request-context-attribute: request
    prefer-file-system-access: false
    settings.number_format: 0.##
# mybatis
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.itmuch.cloud.study.payment.entity
# eureka
eureka:
  instance:
    hostname: 172.16.63.228
    appname: payment-service
    instance-id: http://172.16.63.228:${server.port}
    prefer-ip-address: true
    health-check-url-path: /health
    ip-address: 172.16.63.228
  client:
    service-url:
       defaultZone: http://111.231.189.44:8761/eureka
#swagger
swagger:
  base-package: com.itmuch.cloud.study.payment.controller
# logging
logging:
  level: com.itmuch.cloud.study.payment.entity
  config: classpath:logging-config.xml
##调用微服务超时设置
ribbon:
  ReadTimeout: 6000
  SocketTimeout: 6000

## 易宝支付配置信息
yeepay:
  server_root: https://openapi.yeepay.com/yop-center
  pay_app_key: OPR:10025419533
  app_key: SQKK10025419533
  merchant_no: 10025419533
  quick: SQKKSCENEKJ010
  withhold: SQKKSCENE10
  private_secret_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCujqnrvvPwJCnLvonaqj6ydpLlKEIdjWONYj+vmxcWLDKGsT0DPF4Tj3mx1H+HBDajQPISzqRfUBtDIyqd0oIrC78xbx31I9Kf92F+W/0AS647+OlInfOfND8jjQG/6l/5Py+GtFaP99u4jHslnwIl+TpXFwxpmOm6vZ4dkH/JEhMYv12g5wzTbARFdvXL2B7fzDVLHyAbsRtDhl8xBb6dIF5dyQoB/X63kEGJbgAQBGlc2zWDvLVPlmSBU6ZEYhH3lGLJtJbGOZ5nIRy6ahAq2uzVfwB6zyhkqwCcr4bf50ebqpDChjfHvnVRk7jZZ1p5Aped122YwDdH/7+NYxaHAgMBAAECggEAT45L2Vr9OKxytB5SG+vNiW7LQk/X2jovbieiGPnZSsy39nVe9lOUGNwiPa84tCNyd3NJINM3TQ1ob2/eo3FmzBGdgP1ArRI3k5qev4VTSMg1T7YBNIxwlVWtlRlV+87pEOMAWSdl8FWpuXGlSp8uznnJYhnqGVKM7AQxxQ2vf8bQQzYbl1f2Arn4ECQ0Lk7p/3vHKFINYxb3KTCIQs8LsFuD5fdInRlxNOaEXYXh57MNcvfdNyOio7ZD2ATILXnju1RwUHSxPvVvfuiKmqxH0a+oiGqrFQomqGoFCTdx0ry35lU5O5criGz+VhTawX7ufB4cL/XIsgW/OswOa3dj2QKBgQDrpuA8CrPToXmsxVhrwMl5JSTR/UYYHFWPDrF5y4C2xVaES2hZ+h3kWNjCBsD7lhoBodgGTXx4YuddlLCzU6qFBrs7HE3ZAeWZ+9UaexnRncyhHvQOcMgF95bTBnCKGrUc/y64Z2Fcd+kkhZ3sZ5WCHgkQ3F/+0fiHwOpgBVylEwKBgQC9oUgoslMYVDRC5Tnrh/vZXVH5jHSTbOW/v+US5VL9gv8H/WLnCNvNtLWnMVZUQ9fUwkt+jSjictnm29UcqRliTKXwbl81y3hp002BF7wT0UZl55drkzWdxYglKOnPkzt8aP+Hrlqg6gZ4kHxrwT9jX2aT/zgW1WXfvfoMOBZbPQKBgGLq+7l4bJ/ral3hwQoKNQhLVTdob6HzUt7oNguAJxmRoI2L8dPDMAUIXoSjvSJekbAZtcp/gD4wlhosLjg4aJ3Kg5F+ghcTusN2eK/S+LWK3bjMe3oMUYpfscoHK/ps15XCcGQr0Sy1kQIprG7t1E54OSoAt7MJhJ/HlRqVZZxNAoGAHXqRCSKPoFyWsz+HPYIqOKQ1NiILjU+Ed8aRCdr0h8xxcQCG+3t5EAVjp9YXoYnaZ4y8x7OSA4HvNeA+xPHUrF9V/IZr7qTu1ySuC79w0XPbCcRy2ZpM33XxsDUoA8jTmoeIEcOc+x7mWp+7d9TW0c/m1mL6iTIrYBjcYkHl19ECgYB0j2EN8qiSoO/GIXIZG+Fbjm2IldT5j5Sbuq8+Oj765iudMFyHN6jWo5Oau9SlacX8teYsPAFMAQV9pSz/szxJQLD5l46bRMtYHjA/N/BYKcuDCo4zcfqeaOHWs+XmVGt9c0VvbwDVGUZ8lOW7hewaf5QucPiqNQCrKaD7RqQ0BA==
  public_secret_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6p0XWjscY+gsyqKRhw9MeLsEmhFdBRhT2emOck/F1Omw38ZWhJxh9kDfs5HzFJMrVozgU+SJFDONxs8UB0wMILKRmqfLcfClG9MyCNuJkkfm0HFQv1hRGdOvZPXj3Bckuwa7FrEXBRYUhK7vJ40afumspthmse6bs6mZxNn/mALZ2X07uznOrrc2rk41Y2HftduxZw6T4EmtWuN2x4CZ8gwSyPAW5ZzZJLQ6tZDojBK4GZTAGhnn3bg5bBsBlw2+FLkCQBuDsJVsFPiGh/b6K/+zGTvWyUcu+LUj2MejYQELDO3i2vQXVDk7lVi2/TcUYefvIcssnzsfCfjaorxsuwIDAQAB
  # 回调地址相关
  yeepay_callback_url: http://dev.api.kkd.51kirin.com/callback/repay/order/yeepayCallback
  yeepay_callback_url_v2: http://dev.api.kkd.51kirin.com/callback/repay/order/yeepayCallback/v2
  yeepay_withhold_callback: http://dev.api.kkd.51kirin.com/callback/repay/order/yeepayCallback/withhold

  # 出款记录
  transfer_send_uri: /rest/v1.0/balance/transfer_send
  # 统一鉴权绑卡请求
  auth_bind_card_req_uri: /rest/v1.0/paperorder/unified/auth/request
  # 鉴权绑卡确认
  auth_bind_card_confirm_uri: /rest/v1.0/paperorder/auth/confirm
  # 鉴权绑卡重发
  auth_bind_card_resend_uri: /rest/v1.0/paperorder/auth/resend
  # 鉴权记录查询
  auth_bind_card_query_uri: /rest/v1.0/paperorder/auth/query
  # 解绑银行卡
  unbind_uri: /rest/v1.0/paperorder/unbind/request
  # 支付对账文件下载
  temp_card_pay: /rest/v1.0/paperorder/api/accountcheck/tempcardpay
  # 卡 bin查询
  bank_card_query_uri: /rest/v1.0/paperorder/temppay/bankcardrecord
  # 解绑请求
  paper_order_unbind_uri: /rest/v1.0/paperorder/unbind/request
  # 统一首次支付请求
  union_first_pay_uri: /rest/v1.0/paperorder/unified/firstpay
  # 首次支付短验确认
  first_pay_sms_conf_uri: /rest/v1.0/paperorder/firstpayorder/confirm
  # 首次支付短验重发
  first_pay_sms_resend_uri: /rest/v1.0/paperorder/firstpayorder/resend

  # 统一绑卡支付请求
  bind_card_pay_uri: /rest/v1.0/paperorder/unified/pay
  # 绑卡支付确认
  bind_card_confirm_uri: /rest/v1.0/paperorder/pay/confirm
  # 绑卡支付重发
  bind_card_pay_resend_uri: /rest/v1.0/paperorder/pay/resend
  # 绑卡支付查询
  bind_card_pay_query_uri: /rest/v1.0/paperorder/api/pay/query

  query_customer_amount_uri: /rest/v1.0/balance/query_customer_amount
  # 无感知签约
  auth_nonperceived_uri: rest/v1.0/paperorder/nonperceived/auth/request
  # 查询地址
  payment_query_uri: /rest/v1.0/balance/transfer_query
  # 线下充值
  offline_recharge: /rest/v1.0/std/eaccount/topup
  # 充值回调
  recharge_callback: http://dev.api.kkd.51kirin.com/callback/recharge/yeepayCallback

# 支付宝配置
alipay:
    app_id: 2017071907811942
    private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDFDGu4g/EiBrCPr/Ik2ROdmSdxSp2OCjSgG4/S6sD+dt//oQOZP4FW9Fu1/IDd1pjyz0vJFEm8e1M79rVb7us+aZG7s45rIYPKe7gt+oOsXeKcw+CRR99HytUZug4u/kZIYr63DbAj3H55cLXmATaz/sF/9Egm6jXITxviLjSuEMxqgdAD766lmlJAhOsNk7vusdeGtBwYsA8EhS0xglOFjzehjX6PSe8zVRn01enkC+f/OSpMvl0l8ujI1Cud9sJdSJBlvN4TRuWAKgIk1/ks9tQcm1JCudmxYzMt1umiPJpqmhBdhQGhNugMLcvSOlP5ELOCq+ujurH7oUUE6GCJAgMBAAECggEBAKP3T/O8JvzPYEBQgkfTMpVjigSluDEnoN7R0H4Lxgh41rAaRapRw8idkWr/8COonKD/ieqKrUjfvkUZZ5RWXP4UTqZIJWxT+RyWko3/9W2KujUEcWuyyMMuruC3h3HnOIinUld0Vmug4MUg2tvHisOAa3eTyC5JmfNSkLtHA6MK9REKgZo+utlBhRoJT6MHeqhQT+Z4Mfzh/2atrjeN3emUTlqN16gxRjhYqF/s0knE5bLNtUg01MgiyF75Dy9BQbP5WKZOMKsyxS1JFPJNCLOsm1AT6kMiFaAKfeWjXxpliV+dETvLQXOWBHtT1r7loTwlbI2XckAA1tL4KKZBoXkCgYEA7XEEDduVgaNxAT+0P3YN+Lw0n73TzT0Bc5umlLpwqLBR0fHafbwkq3InwWKeDPPsd5hwoaGOqfWazYvXI3bj5orK4+ZpYB0faJEByCUnIHsQn/0Ot0O/rG94UsJv/4MWdUeatgNmUhNjibOAziOeePvfJAWPdsDttiE5k2613q8CgYEA1HMt7H8yEmHgd+I0ytEgPp8JOGQp8OQ+m9HPhckKczBpcIuBTuQidwSyM4Lv8fAF+sXMlHh6TowoX0diYact9/RGlA904gJ+WZXx8LuV8XyrPQLVQM3HdxbSteg8nYCIyuWo0FqRdySjSfxKQBM3N85g9eBeKxzTp73BddN5wkcCgYEA4NZFyoGFvu5vkYkrO3SkokZFZoYwS4ZbG4fmY6twBqx/rdfg13MTHi3Iq3ygwQ8xecYl0UfUeegSIFUs8W4hPCttGAUU/2hUV4YIM+fKdx1Rjs3n424J0FT1kRiBSWhuGbwmKfhqKYomlTwe2hQsec+3arrBMOhbsD0h8hPBsA0CgYBHf5vtA8GuPhJ1RkPOHiNj79ICkHMtByOq/SmCNO63ZYuWvNx/2Hdg5suyWla2bbkVdIwtS36eAL11k2igxMrLsAIwwiLsDTrIm5YZFoiYBQT8O3/Zl2eRxLSVU9tShneDEVeHB3P9TO9HbwjuF4l11pb7KM+IYuM4iLwbE1je8QKBgEKeGmRvEgcm6+o/IVTziIC96Z5dbMMyJxHCK1WLQa2AFAQTQe0Mz2rsqJH0g0n1OybXI1hhFp6sKBdN1D6oBeU9fp+aJiX5zFLNIQlZtXfZMyafa81dkfwJ4fVdk2I0LBFX8kUHXNx303uFVjSGdX0Uae8bUvfqXWipvi5wlQkc
    pulic_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxQxruIPxIgawj6/yJNkTnZkncUqdjgo0oBuP0urA/nbf/6EDmT+BVvRbtfyA3daY8s9LyRRJvHtTO/a1W+7rPmmRu7OOayGDynu4LfqDrF3inMPgkUffR8rVGboOLv5GSGK+tw2wI9x+eXC15gE2s/7Bf/RIJuo1yE8b4i40rhDMaoHQA++upZpSQITrDZO77rHXhrQcGLAPBIUtMYJThY83oY1+j0nvM1UZ9NXp5Avn/zkqTL5dJfLoyNQrnfbCXUiQZbzeE0blgCoCJNf5LPbUHJtSQrnZsWMzLdbpojyaapoQXYUBoTboDC3L0jpT+RCzgqvro7qx+6FFBOhgiQIDAQAB
    server_url: https://openapi.alipay.com/gateway.do
    notify_domain: http://www.livtrip.com/alipay/notify.do
# 调用远程微服务
feign:
  remote:
      ##调用商品微服务名称
      commodity-service: commodity-service
      ##调用账户微服务名称
      account-service: account-service
      ##调用订单微服务名称
      order-service: order-service

