server:
  port: 8765
# druid
spring:
  application:
    name: payment-service
  datasource:
    druid:
      url: jdbc:mysql://47.75.85.48:3306/spring-cloud-test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: MyNewPass4!
  aop:
    auto: true
  freemarker:
    request-context-attribute: request
    prefer-file-system-access: false
    settings.number_format: 0.##
# mybatis
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.itmuch.cloud.study.payment.entity
# eureka
eureka:
  instance:
    hostname: localhost
    appname: payment-service
    instance-id: payment-service:port-8765
    prefer-ip-address: true
    health-check-url-path: /health
  client:
    service-url:
       defaultZone: http://111.231.189.44:8761/eureka
#swagger
swagger:
  base-package: com.itmuch.cloud.study.payment.controller
# logging
logging:
  level: com.itmuch.cloud.study.payment.entity
  config: classpath:logging-config.xml
##调用微服务超时设置
ribbon:
  ReadTimeout: 6000
  SocketTimeout: 6000
# 调用远程微服务
feign:
  remote:
      ##调用商品微服务名称
      commodity-service: commodity-service
      ##调用账户微服务名称
      account-service: account-service
      ##调用订单微服务名称
      order-service: order-service

