server:
  port: 8763
# druid
spring:
  application:
    name: order-service
  datasource:
    druid:
      url: jdbc:mysql://47.75.85.48:3306/spring-cloud-test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: MyNewPass4!
  redis:
      database: 0           #  Redis数据库索引（默认为0）
      host: 172.17.10.204   #  Redis服务器地址 （默认为127.0.0.1）
      port: 6379            #  Redis服务器连接端口 （默认为6379）
      password:             #  Redis服务器连接密码（默认为空）
      pool:
        max-active: 8       # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle:  8        # 连接池中的最大空闲连接
      timeout: 0       # 连接超时时间
  aop:
    auto: true
  freemarker:
    request-context-attribute: request
    prefer-file-system-access: false
    settings.number_format: 0.##
# mybatis
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.itmuch.cloud.study.order.entity
# eureka
eureka:
  instance:
    hostname: localhost
    appname: order-service
    instance-id: order-service:port-8763
    prefer-ip-address: true
    health-check-url-path: /health
  client:
    service-url:
       defaultZone: http://111.231.189.44:8761/eureka
#swagger
swagger:
  base-package: com.itmuch.cloud.study.order.controller
# logging
logging:
  level: com.itmuch.cloud.study.order.entity
  config: classpath:logging-config.xml

##调用微服务超时设置
ribbon:
  ReadTimeout: 6000
  SocketTimeout: 6000

# zookeeper 配置
curator:
  retryCount: 5 #重试次数
  elapsedTimeMs: 5000 #重试间隔时间
  connectString: 111.231.189.44:2181 # zookeeper 地址
  sessionTimeoutMs: 60000 # session超时时间
  connectionTimeoutMs: 5000 # 连接超时时间
# 调用远程微服务
feign:
  remote:
    commodity-service: commodity-service

